# Generated by Django 4.0.6 on 2022-09-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_project_project_url_alter_project_code_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='orderNum',
            field=models.IntegerField(default=1),
        ),
    ]
