# Generated by Django 4.0.6 on 2022-08-29 09:55

from django.db import migrations, models
import experiences.models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_alter_experience_description2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='picture',
            field=models.ImageField(blank=True, default='', max_length=1000, upload_to=experiences.models.project_image_directory_path),
        ),
    ]
