# Generated by Django 4.0.6 on 2022-08-29 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0003_experience_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='experience',
            name='picture',
        ),
        migrations.AddField(
            model_name='experience',
            name='lien',
            field=models.CharField(max_length=2500, null=True),
        ),
    ]
