# Generated by Django 4.0.6 on 2022-09-02 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0006_alter_experience_lien'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='queryParams',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='experience',
            name='date_fin',
            field=models.DateField(blank=True, null=True),
        ),
    ]
