# Generated by Django 4.0.6 on 2022-09-02 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0007_experience_queryparams_alter_experience_date_fin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='queryParams',
            field=models.JSONField(blank=True, default={'keywords': '', 'languages': [''], 'tags': ['']}, null=True),
        ),
    ]
